# Generated by Django 4.2.1 on 2023-06-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_alter_userbosch_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='categoria',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='categoria',
            field=models.ManyToManyField(to='solicitacoes.categoria'),
        ),
    ]
