# Generated by Django 4.2.1 on 2023-06-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0006_rename_categoriaaas_pedidos_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='categoria',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.categoria'),
            preserve_default=False,
        ),
    ]
