# Generated by Django 4.2.1 on 2023-06-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0007_remove_pedidos_categoria_pedidos_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='anexo_desenho',
        ),
    ]
