# Generated by Django 4.2.1 on 2023-06-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0008_remove_pedidos_anexo_desenho'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='anexo_desenho',
            field=models.ManyToManyField(to='solicitacoes.files'),
        ),
    ]
