# Generated by Django 4.2.1 on 2023-06-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0009_pedidos_anexo_desenho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='blank_area',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='bloco_k',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='nome_do_projeto',
        ),
    ]
