# Generated by Django 4.2.1 on 2023-06-22 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0011_alter_pedidos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
