# Generated by Django 4.2.1 on 2023-07-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0012_alter_pedidos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='anexo',
            field=models.FileField(upload_to=''),
        ),
    ]
