# Generated by Django 4.2.1 on 2023-07-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0013_alter_files_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='anexo',
            field=models.FileField(upload_to='media'),
        ),
    ]
