# Generated by Django 4.2.1 on 2023-07-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0014_alter_files_anexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='anexo',
        ),
    ]
