# Generated by Django 4.2.1 on 2023-07-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0016_files_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='grupo',
            field=models.CharField(blank=True, default=0, max_length=10),
            preserve_default=False,
        ),
    ]
