# Generated by Django 4.2.1 on 2023-07-12 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0018_userbosch_justificativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.categoria'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='local_debito_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.localdebito'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='n_solicitacao_executada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.pedidos'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.setor'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='tipo_de_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.tiposervico'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='tipo_debito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.tipodebito'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
