# Generated by Django 4.2.1 on 2023-07-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0019_alter_pedidos_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='n_solicitacao_executada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
