# Generated by Django 4.2.1 on 2023-07-18 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0021_remove_pedidos_anexo_desenho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramal', models.CharField(max_length=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('local_debito_numero', models.IntegerField()),
                ('prazo_pretendido', models.DateField()),
                ('descricao', models.TextField(max_length=200)),
                ('n_desenho', models.CharField(max_length=10)),
                ('grupo', models.CharField(blank=True, max_length=10)),
                ('solicitacao_semelhante', models.BooleanField(default=False)),
                ('n_solicitacao_executada', models.IntegerField(blank=True, null=True)),
                ('anexo_desenho', models.ManyToManyField(to='solicitacoes.files')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.categoria')),
                ('local_debito_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.localdebito')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.setor')),
                ('tipo_de_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.tiposervico')),
                ('tipo_debito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.tipodebito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
