# Generated by Django 4.2.1 on 2023-07-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0022_files_pedidos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Error',
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='descricao',
            field=models.TextField(),
        ),
    ]
